import { useState, useEffect } from "react";
import { getAllDietLogs } from "../api";

export default function ManageDietLogs() {
    const [logs, setLogs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [viewLog, setViewLog] = useState(null);

    const fetchData = () => {
        setLoading(true);
        getAllDietLogs()
            .then((res) => {
                setLogs(res.data.data);
            })
            .catch(() => { })
            .finally(() => setLoading(false));
    };

    useEffect(() => { fetchData(); }, []);

    // Parse AI plan JSON safely
    const parseAiPlan = (planStr) => {
        try { return JSON.parse(planStr); } catch { return null; }
    };

    if (loading) return <div className="spinner">Loading...</div>;

    return (
        <div>
            <div className="page-header">
                <h1>📜 User Diet Logs</h1>
                <p>View and manage all diet logs generated by users</p>
            </div>

            <div className="card">
                <h2>All System Logs</h2>
                {logs.length === 0 ? (
                    <p style={{ color: "var(--text-muted)", marginTop: 12 }}>No logs found in the system.</p>
                ) : (
                    <div className="table-wrap" style={{ marginTop: 12 }}>
                        <table>
                            <thead>
                                <tr>
                                    <th>User</th>
                                    <th>Date</th>
                                    <th>Calories</th>
                                    <th>Type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {logs.map((log) => (
                                    <tr key={log._id}>
                                        <td>
                                            <strong>{log.user?.name}</strong><br />
                                            <span style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>{log.user?.email}</span>
                                        </td>
                                        <td>{new Date(log.date).toLocaleDateString()}</td>
                                        <td><strong>{log.totalCalories}</strong> kcal</td>
                                        <td>
                                            {log.aiGeneratedPlan ? (
                                                <span className="badge badge-info">AI Plan</span>
                                            ) : (
                                                <span className="badge badge-success">Manual</span>
                                            )}
                                        </td>
                                        <td>
                                            <button className="btn btn-outline btn-sm" onClick={() => setViewLog(log)}>
                                                View Details
                                            </button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* View Diet Log Modal */}
            {viewLog && (
                <div className="modal-overlay" onClick={() => setViewLog(null)}>
                    <div className="modal" style={{ maxWidth: 600, maxHeight: "85vh", overflowY: "auto" }} onClick={(e) => e.stopPropagation()}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
                            <h2 style={{ margin: 0 }}>Diet Log Details</h2>
                            <button className="btn btn-outline btn-sm" onClick={() => setViewLog(null)}>✕ Close</button>
                        </div>

                        <div className="user-card" style={{ padding: 16, marginBottom: 16, background: "rgba(255,255,255,0.03)", borderRadius: 12 }}>
                            <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", textTransform: "uppercase" }}>User Profile</div>
                            <div style={{ fontSize: "1.1rem", fontWeight: 700 }}>{viewLog.user?.name}</div>
                            <div style={{ color: "var(--text-muted)" }}>{viewLog.user?.email}</div>
                        </div>

                        <div style={{ display: "flex", gap: 16, marginBottom: 16 }}>
                            <div className="stat-card" style={{ flex: 1, padding: 14 }}>
                                <div className="stat-val" style={{ fontSize: "1.3rem" }}>{viewLog.totalCalories}</div>
                                <div className="stat-label">Calories</div>
                            </div>
                            <div className="stat-card" style={{ flex: 1, padding: 14 }}>
                                <div className="stat-val" style={{ fontSize: "1.3rem" }}>{new Date(viewLog.date).toLocaleDateString()}</div>
                                <div className="stat-label">Date</div>
                            </div>
                            <div className="stat-card" style={{ flex: 1, padding: 14 }}>
                                <div className="stat-val" style={{ fontSize: "1.3rem" }}>{viewLog.aiGeneratedPlan ? "🤖" : "✍️"}</div>
                                <div className="stat-label">{viewLog.aiGeneratedPlan ? "AI Plan" : "Manual"}</div>
                            </div>
                        </div>

                        {/* Manual log foods */}
                        {viewLog.foods?.length > 0 && (
                            <div>
                                <h3 style={{ fontSize: "0.95rem", color: "var(--accent)", marginBottom: 8 }}>Foods Logged</h3>
                                <div className="table-wrap">
                                    <table>
                                        <thead>
                                            <tr><th>Food</th><th>Calories</th></tr>
                                        </thead>
                                        <tbody>
                                            {viewLog.foods.map((f, i) => (
                                                <tr key={i}>
                                                    <td>{f.name || f}</td>
                                                    <td>{f.calories ? `${f.calories} kcal` : "—"}</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        )}

                        {/* AI Plan details */}
                        {viewLog.aiGeneratedPlan && (() => {
                            const plan = parseAiPlan(viewLog.aiGeneratedPlan);
                            if (!plan) return <p style={{ color: "var(--text-muted)" }}>Could not parse AI plan data.</p>;
                            return (
                                <div>
                                    <div className="diet-plan" style={{ marginTop: 0 }}>
                                        {["breakfast", "lunch", "dinner", "snacks"].map((meal) => (
                                            plan[meal] && (
                                                <div className="meal-card" key={meal}>
                                                    <h3>
                                                        {meal === "breakfast" ? "🌅 Breakfast" :
                                                            meal === "lunch" ? "🍱 Lunch" :
                                                                meal === "dinner" ? "🌙 Dinner" : "🍿 Snacks"}
                                                    </h3>
                                                    <ul>
                                                        {plan[meal]?.items?.map((item, i) => <li key={i}>{item}</li>)}
                                                    </ul>
                                                    <div className="meal-cal">{plan[meal]?.calories} kcal</div>
                                                </div>
                                            )
                                        ))}
                                        {plan.healthTips && (
                                            <div className="tips-card">
                                                <h3>Health Tips</h3>
                                                <ul>
                                                    {plan.healthTips.map((tip, i) => <li key={i}>{tip}</li>)}
                                                </ul>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            );
                        })()}
                    </div>
                </div>
            )}
        </div>
    );
}
